### ISSUE TITLE
migrate.py TypeError: NoneType

### ISSUE THREAD

**Issue by punderino** [epochengine/ytmusic-to-spotify#1]
python migrate.py
Traceback (most recent call last):
  File "D:\Downloads\ytmusic-to-spotify-main\ytmusic-to-spotify-main\migrate.py", line 53, in <module>
    main()
  File "D:\Downloads\ytmusic-to-spotify-main\ytmusic-to-spotify-main\migrate.py", line 49, in main
    runner.migrate_library()
  File "D:\Downloads\ytmusic-to-spotify-main\ytmusic-to-spotify-main\migrate.py", line 13, in migrate_library
    liked_songs = self.yt_music_client.get_liked_songs()
  File "D:\Downloads\ytmusic-to-spotify-main\ytmusic-to-spotify-main\ytmusic.py", line 19, in get_liked_songs
    album = t['album']['name']
TypeError: 'NoneType' object is not subscriptable
PS D:\Downloads\ytmusic-to-spotify-main\ytmusic-to-spotify-main>

I've ran both the test and they seem to be fine. If I misconfigure either the JSON or the .ini file it errors out before that so I'm not sure what this is about.

**Comment by epochengine** [comment]
@punderino apologies, I had no notification of this issue and haven't looked at this project for a while.

I've just fixed this in a741afb99436ce0b1d3c8a5b3cbe5c7e4456ead9.
